config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  resources :report_requests, only: [:new, :create, :index, :show]
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :key_indicator_reports, only: [:create]
    end
  end
end

app/views/shared/navbars/_navbar_original.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Histórico de consultas", report_requests_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Nova consulta",  new_report_request_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "logo.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item d-md-none d-lg-none">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/navbars/_navbar_w_bootstrap4.html.erb
<div class="navbar bg-white py-3 px-4">
  <i class="fas fa-smile"></i>
  <div class="nav-bar-right d-flex align-items-center">
    <%= link_to "Profile", "#", class: "px-3 d-none d-sm-block" %>
    <%= link_to "Dashboard", "#", class: "px-3 d-none d-sm-block" %>
    <%= link_to "Login", "#", class: "px-3 d-none d-sm-block" %>
    <div class="dropdown  d-none d-sm-block">
      <%= image_tag "http://www.placehold.it/40x40", class: "rounded-circle px-3", alt:"avatar", type: "image", id: "dropdownMenuButton", data: { toggle:"dropdown" }, aria: { haspopup:"true", expanded: "false" } %>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= link_to "Action", "#", class: "dropdown-item" %>
        <%= link_to "Another action", "#", class: "dropdown-item" %>
        <%= link_to "Something else here", "#", class: "dropdown-item" %>
      </div>
    </div>
  </div>
  <div class="dropdown burger d-block d-sm-none">
    <i class="fas fa-bars" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
     <%= link_to "Action", "#", class: "dropdown-item" %>
     <%= link_to "Another action", "#", class: "dropdown-item" %>
     <%= link_to "Something else here", "#", class: "dropdown-item" %>
   </div>
 </div>
</div>